export const MAIN_ROUTE = "/"
export const TICKETS_ROUTE = "order/tickets"
export const TRAIN_INFO_ROUTER = "order/tickets/train"
export const PASSENGERS_ROUTER = "order/tickets/passengers"
export const PAYMENT_ORDER_ROUTE = "order/tickets/payment"
export const CONFIRMATION_ORDER_ROUTE = "order/tickets/payment/сonfirmation"
export const SUCCESS_ORDER_ROUTE = "order/tickets/payment/success"
